// <auto-generated />
namespace EnterpriseDataPipeline.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class JobStatusNew3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(JobStatusNew3));
        
        string IMigrationMetadata.Id
        {
            get { return "201508110104011_JobStatusNew3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
