// <auto-generated />
namespace EnterpriseDataPipeline.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_KafkaTopcis : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_KafkaTopcis));
        
        string IMigrationMetadata.Id
        {
            get { return "201602192353055_Add_KafkaTopcis"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
