// <auto-generated />
namespace SV4U.EDPL.DynamicMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class JobTB1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(JobTB1));
        
        string IMigrationMetadata.Id
        {
            get { return "201508041023222_JobTB1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
